config/routes.rb
Rails.application.routes.draw do
  resources :gallery_attachments
  resources :galleries

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	has_many :gallery_attachments
	accepts_nested_attributes_for :gallery_attachments
end

app/models/gallery_attachment.rb
class GalleryAttachment < ActiveRecord::Base
	belongs_to :gallery
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery_attachments = @gallery.gallery_attachments.all
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
    @gallery_attachment = @gallery.gallery_attachments.build
  end

  # GET /galleries/1/edit
  def edit
    @gallery_attachments = @gallery.gallery_attachments.all
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        params[:gallery_attachments]['image'].each do |image|
          @gallery_attachment = @gallery.gallery_attachments.create!(:image => image)
        end
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, gallery_attachments_attributes: [:id, :gallery_id, :image])
    end
end

app/controllers/gallery_attachments_controller.rb
class GalleryAttachmentsController < ApplicationController
  before_action :set_gallery_attachment, only: [:show, :edit, :update, :destroy]

  # GET /gallery_attachments
  # GET /gallery_attachments.json
  def index
    @gallery_attachments = GalleryAttachment.all
  end

  # GET /gallery_attachments/1
  # GET /gallery_attachments/1.json
  def show
  end

  # GET /gallery_attachments/new
  def new
    @gallery_attachment = GalleryAttachment.new
  end

  # GET /gallery_attachments/1/edit
  def edit
  end

  # POST /gallery_attachments
  # POST /gallery_attachments.json
  def create
    @gallery_attachment = GalleryAttachment.new(gallery_attachment_params)

    respond_to do |format|
      if @gallery_attachment.save
        format.html { redirect_to @gallery_attachment, notice: 'Gallery attachment was successfully created.' }
        format.json { render :show, status: :created, location: @gallery_attachment }
      else
        format.html { render :new }
        format.json { render json: @gallery_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gallery_attachments/1
  # PATCH/PUT /gallery_attachments/1.json
  def update
    respond_to do |format|
      if @gallery_attachment.update(gallery_attachment_params)
        format.html { redirect_to @gallery_attachment.gallery, notice: 'Gallery attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery_attachment }
      else
        format.html { render :edit }
        format.json { render json: @gallery_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gallery_attachments/1
  # DELETE /gallery_attachments/1.json
  def destroy
    @gallery_attachment.destroy
    respond_to do |format|
      format.html { redirect_to gallery_attachments_url, notice: 'Gallery attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery_attachment
      @gallery_attachment = GalleryAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_attachment_params
      params.require(:gallery_attachment).permit(:gallery_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_attachments_helper.rb
module GalleryAttachmentsHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.fields_for :gallery_attachments do |f| %>
    <div class="field">
      <%= f.file_field :image, multiple: true, name: "gallery_attachments[image][]" %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.name %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gallery.name %>
</p>
<p>
	<% @gallery_attachments.each do |g| %>
		<%= image_tag g.image_url(:thumb) %>
		<%= link_to "Edit Attachment", edit_gallery_attachment_path(g) %>
	<% end %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/gallery_attachments/_form.html.erb
<%= image_tag @gallery_attachment.image_url(:thumb) %>
<%= form_for(@gallery_attachment) do |f| %>
  <% if @gallery_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery_attachment.errors.count, "error") %> prohibited this gallery_attachment from being saved:</h2>

      <ul>
      <% @gallery_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallery_attachments/edit.html.erb
<h1>Editing Gallery Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery_attachment %> |
<%= link_to 'Back', gallery_attachments_path %>

app/views/gallery_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gallery Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Gallery</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gallery_attachments.each do |gallery_attachment| %>
      <tr>
        <td><%= gallery_attachment.gallery_id %></td>
        <td><%= gallery_attachment.image %></td>
        <td><%= link_to 'Show', gallery_attachment %></td>
        <td><%= link_to 'Edit', edit_gallery_attachment_path(gallery_attachment) %></td>
        <td><%= link_to 'Destroy', gallery_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery attachment', new_gallery_attachment_path %>

app/views/gallery_attachments/new.html.erb
<h1>New Gallery Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_attachments_path %>

app/views/gallery_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gallery:</strong>
  <%= @gallery_attachment.gallery_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @gallery_attachment.image %>
</p>

<%= link_to 'Edit', edit_gallery_attachment_path(@gallery_attachment) %> |
<%= link_to 'Back', gallery_attachments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultipleImagesCarrierwave</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>